import { useEffect,useState } from 'react'
import { useAgents } from '../stores/agentStore'
import { createReply,listConversations,listMessages,patchConversation,reviewMessage } from '../api/inbox'
import type { InboxConversation,InboxMessage } from '../types'

export default function Inbox(){
 const {agents,fetch}=useAgents();const [items,setItems]=useState<InboxConversation[]>([]);const [active,setActive]=useState<InboxConversation>();const [messages,setMessages]=useState<InboxMessage[]>([]);const [reply,setReply]=useState('');const [filter,setFilter]=useState('OPEN')
 const load=async()=>setItems(await listConversations());useEffect(()=>{fetch();load()},[fetch]);
 const open=async(c:InboxConversation)=>{setActive(c);setMessages(await listMessages(c.id))};
 useEffect(()=>{if(!active)return;const t=setInterval(async()=>setMessages(await listMessages(active.id)),5000);return()=>clearInterval(t)},[active]);
 const patch=async(value:Partial<InboxConversation>)=>{if(!active)return;const updated=await patchConversation(active.id,value);setActive(updated);await load()};
 const send=async()=>{if(!active||!reply.trim())return;await createReply(active.id,reply.trim());setReply('');setMessages(await listMessages(active.id))};
 const review=async(m:InboxMessage,ok:boolean)=>{await reviewMessage(m.id,ok);if(active)setMessages(await listMessages(active.id))};
 const visible=items.filter(i=>filter==='ALL'||i.status===filter)
 return <div className="h-full min-h-0 flex"><aside className="w-[360px] shrink-0 border-r border-term-border flex flex-col bg-black/20"><div className="p-5 border-b border-term-border"><h1 className="text-xl font-bold"><span className="text-term-green">#</span> inbox</h1><p className="text-xs text-term-muted mt-1">Todos os canais em uma caixa de entrada.</p><select className="field mt-4" value={filter} onChange={e=>setFilter(e.target.value)}><option value="OPEN">abertas</option><option value="WAITING">aguardando</option><option value="CLOSED">concluídas</option><option value="ALL">todas</option></select></div><div className="overflow-y-auto flex-1">{visible.map(c=><button key={c.id} onClick={()=>open(c)} className={`w-full text-left p-4 border-b border-term-border hover:bg-white/5 ${active?.id===c.id?'bg-term-green/10':''}`}><div className="flex gap-2"><span className="font-semibold truncate flex-1">{c.contactName}</span>{c.priority==='HIGH'&&<span className="badge border-term-red/40 text-term-red">urgente</span>}</div><div className="text-xs text-term-muted truncate mt-1">{c.summary||'Sem resumo'}</div><div className="text-[10px] text-term-muted mt-2">{agents.find(a=>a.id===c.assignedAgentId)?.name||'sem agente'}</div></button>)}</div></aside>
 <main className="flex-1 min-w-0 flex flex-col">{!active?<div className="h-full grid place-items-center text-term-muted">Selecione uma conversa.</div>:<><header className="p-4 border-b border-term-border flex items-center gap-3"><div><div className="font-bold">{active.contactName}</div><div className="text-xs text-term-muted">{active.externalContactId}</div></div><select className="field max-w-48 ml-auto" value={active.assignedAgentId||''} onChange={e=>patch({assignedAgentId:Number(e.target.value)})}><option value="">sem agente</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className="field max-w-40" value={active.priority} onChange={e=>patch({priority:e.target.value as InboxConversation['priority']})}><option value="LOW">baixa</option><option value="NORMAL">normal</option><option value="HIGH">alta</option></select><select className="field max-w-44" value={active.status} onChange={e=>patch({status:e.target.value as InboxConversation['status']})}><option value="OPEN">aberta</option><option value="WAITING">aguardando</option><option value="CLOSED">concluída</option></select></header><div className="flex-1 overflow-y-auto p-6 space-y-4">{messages.map(m=><div key={m.id} className={`flex ${m.direction==='OUTBOUND'?'justify-end':'justify-start'}`}><div className={`max-w-[75%] panel p-4 ${m.direction==='OUTBOUND'?'border-term-green/30':''}`}><div className="text-[10px] text-term-muted uppercase mb-1">{m.direction==='INBOUND'?'contato':m.senderType} · {m.status}</div><div className="whitespace-pre-wrap text-sm">{m.content}</div>{m.status==='PENDING_APPROVAL'&&<div className="flex gap-2 mt-3"><button className="btn btn-primary" onClick={()=>review(m,true)}>aprovar</button><button className="btn btn-danger" onClick={()=>review(m,false)}>rejeitar</button></div>}</div></div>)}</div><footer className="p-4 border-t border-term-border flex gap-2"><textarea className="field min-h-16" value={reply} onChange={e=>setReply(e.target.value)} placeholder="Escreva uma resposta para aprovação..."/><button className="btn btn-primary" onClick={send}>preparar</button></footer></>}</main></div>
}
